[project]
name = 'Blockchain-Based-Hotel-Group-Booking-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.attrition-management]
path = 'contracts/attrition-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.property-verification]
path = 'contracts/property-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.room-block]
path = 'contracts/room-block.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
